# Generated by Django 5.0.3 on 2024-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
