# Generated by Django 5.0.3 on 2024-03-18 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_rolepermission_permission_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
